export const defaultWholesaleInfo: Record<string, any> = {
  eyebrow: "Kurumsal",
  title: "İşinizi Güçlendiren Profesyonel Çözümler",
  description: "İşletmelerin ve atölyelerin ihtiyaç duyduğu yüksek kaliteli ürün ve ekipmanları toptan avantajlarla sunuyoruz.",
  hero_image: "/brand/placeholder.svg",
  hero_cta1_text: "Teklif Talebi Oluştur", hero_cta1_href: "#quote-form",
  hero_cta2_text: "Bize Ulaşın", hero_cta2_href: "/iletisim",
  feat1_title: "Toptan Fiyat Avantajı", feat1_desc: "Yüksek adetli alımlarda özel fiyatlandırma fırsatları.", feat1_icon: "tag",
  feat2_title: "Güvenilir Tedarik", feat2_desc: "Stoktan hızlı teslimat ve kesintisiz tedarik.", feat2_icon: "package",
  feat3_title: "Uzman Destek", feat3_desc: "İhtiyacınıza uygun ürün ve çözüm önerileri.", feat3_icon: "headphones",
  feat4_title: "Özel Çözümler", feat4_desc: "Projenize özel ürün, paketleme ve lojistik çözümleri.", feat4_icon: "wrench",
  feat5_title: "Fatura ve Ödeme", feat5_desc: "Kolay fatura yönetimi ve esnek ödeme seçenekleri.", feat5_icon: "receipt",
  feat6_title: "Hızlı Sevkiyat", feat6_desc: "Türkiye geneli aynı gün kargo ve güvenli teslimat.", feat6_icon: "truck",
  why_title: "Neden Bizi Seçmelisiniz?", why_desc: "Geniş ürün yelpazemiz ve güçlü tedarik ağımızla işletmelerin üretim gücünü artırıyoruz.",
  stat1_value: "10.000+", stat1_label: "Ürün Çeşidi", stat1_icon: "tag",
  stat2_value: "500+", stat2_label: "Kurumsal Müşteri", stat2_icon: "users",
  stat3_value: "Hızlı", stat3_label: "Teslimat", stat3_icon: "truck",
  stat4_value: "%100", stat4_label: "Müşteri Memnuniyeti", stat4_icon: "award",
  target_title: "Kimler İçin Uygun?",
  target_item1: "Sanayi ve üretim tesisleri", target_item2: "İnşaat ve taahhüt firmaları",
  target_item3: "Otomotiv servis ve yedek parça bayileri", target_item4: "Perakende satış yapan işletmeler",
  target_item5: "Kamu kurum ve kuruluşları", target_item6: "Özel atölyeler ve teknik servisler",
  process_title: "Toptan Satış Sürecimiz",
  step1_title: "Talep", step1_desc: "İhtiyacınızı ve istediğiniz ürünleri bize iletin.", step1_icon: "file-text",
  step2_title: "Teklif", step2_desc: "Size özel fiyat ve teslimat teklifimizi sunalım.", step2_icon: "receipt",
  step3_title: "Sipariş", step3_desc: "Teklifinizi onaylayın, siparişinizi oluşturalım.", step3_icon: "package-check",
  step4_title: "Teslimat", step4_desc: "Ürünlerinizi hızlı ve güvenli şekilde teslim edelim.", step4_icon: "truck",
  step5_title: "Destek", step5_desc: "Satış sonrası teknik destekte yanınızda olalım.", step5_icon: "shield-check",
  step6_title: "Memnuniyet", step6_desc: "Kesintisiz iş ortaklığı ve müşteri memnuniyeti takibi.", step6_icon: "award",
  form_title: "Size Özel Teklif Alın", form_desc: "İhtiyacınızı belirtin, en kısa sürede size geri dönüş yapalım.",
  phone: "", phone_sub: "Hafta içi 09:00 - 18:00",
  email: "", email_sub: "Ortalama yanıt süresi: 2 saat",
  address: "",
}
