import { NextRequest, NextResponse } from "next/server"
import { revalidatePath } from "next/cache"
import { getAdminSession } from "@lib/admin/auth"
import { query } from "@lib/admin/db"
import { isSafePublicImageUrl } from "@lib/security/public-assets"
import { persistInlineImageUrl } from "@lib/storage/persist-inline-image"

async function ensureSeoColumns() {
  try {
    await query(`
      ALTER TABLE theme_settings 
      ADD COLUMN IF NOT EXISTS maintenance_mode BOOLEAN DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS maintenance_message TEXT DEFAULT 'Sitemiz şu anda planlı bakım çalışması sebebiyle geçici olarak hizmet verememektedir. Kısa süre sonra tekrar hizmetinizde olacağız.',
      ADD COLUMN IF NOT EXISTS seo_meta_title TEXT,
      ADD COLUMN IF NOT EXISTS seo_meta_description TEXT,
      ADD COLUMN IF NOT EXISTS seo_meta_keywords TEXT,
      ADD COLUMN IF NOT EXISTS seo_google_verification TEXT,
      ADD COLUMN IF NOT EXISTS seo_ga4_id TEXT,
      ADD COLUMN IF NOT EXISTS seo_gtm_id TEXT,
      ADD COLUMN IF NOT EXISTS custom_head_scripts TEXT,
      ADD COLUMN IF NOT EXISTS custom_body_scripts TEXT,
      ADD COLUMN IF NOT EXISTS seo_og_image_url TEXT,
      ADD COLUMN IF NOT EXISTS seo_canonical_url TEXT,
      ADD COLUMN IF NOT EXISTS seo_indexing_enabled BOOLEAN DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS seo_title_separator TEXT DEFAULT '|',
      ADD COLUMN IF NOT EXISTS seo_product_title_template TEXT DEFAULT '%urun_adi% %ayirici% %site_adi%',
      ADD COLUMN IF NOT EXISTS seo_product_desc_template TEXT DEFAULT '%urun_adi% ürününü %site_adi% üzerinde inceleyin.',
      ADD COLUMN IF NOT EXISTS seo_category_title_template TEXT DEFAULT '%kategori% Modelleri ve Fiyatları %ayirici% %site_adi%',
      ADD COLUMN IF NOT EXISTS seo_category_desc_template TEXT DEFAULT '%kategori% ürünlerini %site_adi% üzerinde inceleyin.',
      ADD COLUMN IF NOT EXISTS seo_brand_title_template TEXT DEFAULT '%marka% Ürünleri ve Fiyatları %ayirici% %site_adi%',
      ADD COLUMN IF NOT EXISTS seo_brand_desc_template TEXT DEFAULT '%marka% ürünlerini %site_adi% üzerinde inceleyin.',
      ADD COLUMN IF NOT EXISTS seo_blog_title_template TEXT DEFAULT '%yazi_basligi% %ayirici% %site_adi%',
      ADD COLUMN IF NOT EXISTS seo_blog_desc_template TEXT DEFAULT '%yazi_ozeti%',
      ADD COLUMN IF NOT EXISTS seo_page_title_template TEXT DEFAULT '%sayfa_adi% %ayirici% %site_adi%',
      ADD COLUMN IF NOT EXISTS footer_features_active BOOLEAN DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS header_menu_align TEXT DEFAULT 'center',
      ADD COLUMN IF NOT EXISTS header_menu_font_size TEXT DEFAULT '13px',
      ADD COLUMN IF NOT EXISTS header_menu_gap TEXT DEFAULT '16px',
      ADD COLUMN IF NOT EXISTS header_menu_letter_spacing TEXT DEFAULT '0',
      ADD COLUMN IF NOT EXISTS header_menu_font_weight TEXT DEFAULT '600',
      ADD COLUMN IF NOT EXISTS header_menu_text_transform TEXT DEFAULT 'none',
      ADD COLUMN IF NOT EXISTS footer_description TEXT,
      ADD COLUMN IF NOT EXISTS contact_phone TEXT,
      ADD COLUMN IF NOT EXISTS contact_email TEXT,
      ADD COLUMN IF NOT EXISTS contact_address TEXT,
      ADD COLUMN IF NOT EXISTS footer_col2_title TEXT,
      ADD COLUMN IF NOT EXISTS footer_col3_title TEXT,
      ADD COLUMN IF NOT EXISTS footer_col4_title TEXT,
      ADD COLUMN IF NOT EXISTS footer_col5_title TEXT,
      ADD COLUMN IF NOT EXISTS footer_col5_desc TEXT,
      ADD COLUMN IF NOT EXISTS social_instagram TEXT,
      ADD COLUMN IF NOT EXISTS social_facebook TEXT,
      ADD COLUMN IF NOT EXISTS social_youtube TEXT,
      ADD COLUMN IF NOT EXISTS social_linkedin TEXT,
      ADD COLUMN IF NOT EXISTS footer_copyright_text TEXT,
      ADD COLUMN IF NOT EXISTS footer_brand_subtext TEXT,
      ADD COLUMN IF NOT EXISTS footer_mersis_no TEXT,
      ADD COLUMN IF NOT EXISTS footer_kep_address TEXT,
      ADD COLUMN IF NOT EXISTS footer_show_payment_badges BOOLEAN DEFAULT FALSE,
      ADD COLUMN IF NOT EXISTS payment_logo_iyzico TEXT DEFAULT '/brand/placeholder.svg',
      ADD COLUMN IF NOT EXISTS payment_logo_mastercard TEXT DEFAULT '/brand/placeholder.svg',
      ADD COLUMN IF NOT EXISTS payment_logo_visa TEXT DEFAULT '/brand/placeholder.svg',
      ADD COLUMN IF NOT EXISTS payment_logo_amex TEXT DEFAULT '/brand/placeholder.svg',
      ADD COLUMN IF NOT EXISTS payment_logo_troy TEXT DEFAULT '/brand/placeholder.svg',
      ADD COLUMN IF NOT EXISTS footer_features JSONB DEFAULT '[]'::jsonb;
    `)
  } catch (e) {
    // Columns might already exist
  }
}

export async function GET(req: NextRequest) {
  const session = await getAdminSession()
  if (!session) {
    return NextResponse.json({ error: "Yetkisiz erişim." }, { status: 401 })
  }

  try {
    await ensureSeoColumns()
    const settings = await query<any>(
      "SELECT * FROM theme_settings WHERE id = 1"
    )
    if (settings.length > 0) {
      const s = settings[0]
      return NextResponse.json({
        settings: {
          ...s,
          maintenance_mode: Boolean(s.maintenance_mode),
          maintenance_message: s.maintenance_message || "Sitemiz şu anda planlı bakım çalışması sebebiyle geçici olarak hizmet verememektedir. Kısa süre sonra tekrar hizmetinizde olacağız.",
          font_family: s.font_family || "Poppins",
          header_logo_url: s.header_logo_url || "/brand/placeholder.svg",
          header_logo_dark_url: s.header_logo_dark_url || "/brand/placeholder.svg",
          footer_logo_url: s.footer_logo_url || "/brand/placeholder.svg",
          footer_logo_dark_url: s.footer_logo_dark_url || "/brand/placeholder.svg",
          favicon_url: s.favicon_url || "/brand/placeholder.svg",
          admin_logo_url: s.admin_logo_url || "/brand/placeholder.svg",
          mini_logo_url: s.mini_logo_url || "/brand/placeholder.svg",
          header_menu_align: s.header_menu_align || "center",
          header_menu_font_size: s.header_menu_font_size || "13px",
          header_menu_gap: s.header_menu_gap || "16px",
          header_menu_letter_spacing: s.header_menu_letter_spacing || "0",
          header_menu_font_weight: s.header_menu_font_weight || "600",
          header_menu_text_transform: s.header_menu_text_transform || "none",
          seo_title_separator: s.seo_title_separator || "|",
          seo_product_title_template: s.seo_product_title_template || "%urun_adi% %ayirici% %site_adi%",
          seo_product_desc_template: s.seo_product_desc_template || "%urun_adi% ürününü %site_adi% üzerinde inceleyin.",
          seo_category_title_template: s.seo_category_title_template || "%kategori% Modelleri ve Fiyatları %ayirici% %site_adi%",
          seo_category_desc_template: s.seo_category_desc_template || "%kategori% ürünlerini %site_adi% üzerinde inceleyin.",
          seo_brand_title_template: s.seo_brand_title_template || "%marka% Ürünleri ve Fiyatları %ayirici% %site_adi%",
          seo_brand_desc_template: s.seo_brand_desc_template || "%marka% ürünlerini %site_adi% üzerinde inceleyin.",
          seo_blog_title_template: s.seo_blog_title_template || "%yazi_basligi% %ayirici% %site_adi%",
          seo_blog_desc_template: s.seo_blog_desc_template || "%yazi_ozeti%",
          seo_page_title_template: s.seo_page_title_template || "%sayfa_adi% %ayirici% %site_adi%",
          footer_features_active: s.footer_features_active === true,
          footer_description: s.footer_description ?? "",
          contact_phone: s.contact_phone ?? "",
          contact_email: s.contact_email ?? "",
          contact_address: s.contact_address ?? "",
          footer_col2_title: s.footer_col2_title || "KURUMSAL",
          footer_col3_title: s.footer_col3_title || "MÜŞTERİ HİZMETLERİ",
          footer_col4_title: s.footer_col4_title || "YASAL BİLGİLENDİRME",
          footer_col5_title: s.footer_col5_title || "BİZİ TAKİP EDİN",
          footer_col5_desc: s.footer_col5_desc || "Yeniliklerden, kampanyalardan ve içeriklerden haberdar olun.",
          social_instagram: s.social_instagram ?? "",
          social_facebook: s.social_facebook ?? "",
          social_youtube: s.social_youtube ?? "",
          social_linkedin: s.social_linkedin ?? "",
          footer_copyright_text: s.footer_copyright_text || `© ${new Date().getFullYear()} Tüm hakları saklıdır.`,
          footer_brand_subtext: s.footer_brand_subtext ?? "",
          footer_mersis_no: s.footer_mersis_no ?? "",
          footer_kep_address: s.footer_kep_address ?? "",
          footer_show_payment_badges: s.footer_show_payment_badges === true,
          payment_logo_iyzico: s.payment_logo_iyzico || "/brand/placeholder.svg",
          payment_logo_mastercard: s.payment_logo_mastercard || "/brand/placeholder.svg",
          payment_logo_visa: s.payment_logo_visa || "/brand/placeholder.svg",
          payment_logo_amex: s.payment_logo_amex || "/brand/placeholder.svg",
          payment_logo_troy: s.payment_logo_troy || "/brand/placeholder.svg",
          footer_features: s.footer_features || [],
        },
      })
    }
    return NextResponse.json({
      settings: {
        logo_text: "Mağaza",
        header_logo_url: "/brand/placeholder.svg",
        header_logo_dark_url: "/brand/placeholder.svg",
        footer_logo_url: "/brand/placeholder.svg",
        footer_logo_dark_url: "/brand/placeholder.svg",
        favicon_url: "/brand/placeholder.svg",
        admin_logo_url: "/brand/placeholder.svg",
        mini_logo_url: "/brand/placeholder.svg",
        font_family: "Poppins",
        font_size_base: "16px",
        h1_size: "2.5rem",
        h2_size: "2rem",
        h3_size: "1.75rem",
        h4_size: "1.5rem",
        slider_font_title: "Plus Jakarta Sans",
        slider_font_desc: "Inter",
        header_menu_align: "center",
        header_menu_font_size: "13px",
        header_menu_gap: "16px",
        header_menu_letter_spacing: "0",
        header_menu_font_weight: "600",
        header_menu_text_transform: "none",
        seo_meta_title: "Mağaza | Online Mağaza",
        seo_meta_description: "",
        seo_meta_keywords: "",
        seo_indexing_enabled: false,
        seo_title_separator: "|",
        seo_product_title_template: "%urun_adi% %ayirici% %site_adi%",
        seo_product_desc_template: "%urun_adi% ürününü %site_adi% üzerinde inceleyin.",
        seo_category_title_template: "%kategori% Modelleri ve Fiyatları %ayirici% %site_adi%",
        seo_category_desc_template: "%kategori% ürünlerini %site_adi% üzerinde inceleyin.",
        seo_brand_title_template: "%marka% Ürünleri ve Fiyatları %ayirici% %site_adi%",
        seo_brand_desc_template: "%marka% ürünlerini %site_adi% üzerinde inceleyin.",
        seo_blog_title_template: "%yazi_basligi% %ayirici% %site_adi%",
        seo_blog_desc_template: "%yazi_ozeti%",
        seo_page_title_template: "%sayfa_adi% %ayirici% %site_adi%",
        footer_features_active: false,
        footer_description: "",
        contact_phone: "",
        contact_email: "",
        contact_address: "",
        footer_col2_title: "KURUMSAL",
        footer_col3_title: "MÜŞTERİ HİZMETLERİ",
        footer_col4_title: "YASAL BİLGİLENDİRME",
        footer_col5_title: "BİZİ TAKİP EDİN",
        footer_col5_desc: "Yeniliklerden, kampanyalardan ve içeriklerden haberdar olun.",
        social_instagram: "",
        social_facebook: "",
        social_youtube: "",
        social_linkedin: "",
        footer_copyright_text: `© ${new Date().getFullYear()} Mağaza. Tüm hakları saklıdır.`,
        footer_brand_subtext: "",
        footer_mersis_no: "",
        footer_kep_address: "",
        footer_show_payment_badges: false,
        footer_features: [],
      },
    })
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  const session = await getAdminSession(["Admin"])
  if (!session)
    return NextResponse.json({ error: "Yetkisiz işlem." }, { status: 401 })

  try {
    await ensureSeoColumns()
    const body = await req.json()
    // The dedicated Google settings screen owns these fields. A theme save
    // must preserve them when its form does not send them.
    const googleFields = ["seo_google_verification", "seo_ga4_id", "seo_gtm_id", "custom_head_scripts", "custom_body_scripts"] as const
    if (googleFields.some(field => !Object.prototype.hasOwnProperty.call(body, field))) {
      const [existing] = await query<any>("SELECT seo_google_verification, seo_ga4_id, seo_gtm_id, custom_head_scripts, custom_body_scripts FROM theme_settings WHERE id=1")
      for (const field of googleFields) {
        if (!Object.prototype.hasOwnProperty.call(body, field)) body[field] = existing?.[field] || null
      }
    }
    const imageFieldNames = [
      "logo_url",
      "header_logo_url",
      "header_logo_dark_url",
      "footer_logo_url",
      "footer_logo_dark_url",
      "favicon_url",
      "admin_logo_url",
      "mini_logo_url",
      "seo_og_image_url",
      "payment_logo_iyzico",
      "payment_logo_mastercard",
      "payment_logo_visa",
      "payment_logo_amex",
      "payment_logo_troy",
    ] as const
    for (const field of imageFieldNames) {
      body[field] = await persistInlineImageUrl(body[field], field.replace(/_/g, " "))
    }
    const {
      logo_text,
      logo_url,
      font_family,
      font_size_base,
      h1_size,
      h2_size,
      h3_size,
      h4_size,
      slider_font_title,
      slider_font_desc,
      header_logo_url,
      header_logo_dark_url,
      header_logo_height,
      header_logo_alt,
      footer_logo_url,
      footer_logo_dark_url,
      footer_logo_height,
      footer_logo_alt,
      favicon_url,
      admin_logo_url,
      admin_logo_height,
      admin_logo_alt,
      mini_logo_url,
      mini_logo_height,
      mini_logo_alt,
      header_menu_align,
      header_menu_font_size,
      header_menu_gap,
      header_menu_letter_spacing,
      header_menu_font_weight,
      header_menu_text_transform,
      seo_meta_title,
      seo_meta_description,
      seo_meta_keywords,
      seo_google_verification,
      seo_ga4_id,
      seo_gtm_id,
      custom_head_scripts,
      custom_body_scripts,
      seo_og_image_url,
      seo_canonical_url,
      seo_indexing_enabled,
      seo_title_separator,
      seo_product_title_template,
      seo_product_desc_template,
      seo_category_title_template,
      seo_category_desc_template,
      seo_brand_title_template,
      seo_brand_desc_template,
      seo_blog_title_template,
      seo_blog_desc_template,
      seo_page_title_template,
      footer_features_active,
      footer_features,
      footer_description,
      contact_phone,
      contact_email,
      contact_address,
      footer_col2_title,
      footer_col3_title,
      footer_col4_title,
      footer_col5_title,
      footer_col5_desc,
      social_instagram,
      social_facebook,
      social_youtube,
      social_linkedin,
      footer_copyright_text,
      footer_brand_subtext,
      footer_mersis_no,
      footer_kep_address,
      footer_show_payment_badges,
      payment_logo_iyzico,
      payment_logo_mastercard,
      payment_logo_visa,
      payment_logo_amex,
      payment_logo_troy,
    } = body

    const imageFields = [
      logo_url,
      header_logo_url,
      header_logo_dark_url,
      footer_logo_url,
      footer_logo_dark_url,
      favicon_url,
      admin_logo_url,
      mini_logo_url,
      seo_og_image_url,
      payment_logo_iyzico,
      payment_logo_mastercard,
      payment_logo_visa,
      payment_logo_amex,
      payment_logo_troy,
    ].filter(Boolean)
    if (imageFields.some((value) => !isSafePublicImageUrl(value))) {
      return NextResponse.json(
        { error: "Görseller önce medya kütüphanesine yüklenmelidir." },
        { status: 400 }
      )
    }

    await query(
      `INSERT INTO theme_settings (
        id, logo_text, logo_url, font_family, font_size_base, 
        h1_size, h2_size, h3_size, h4_size, slider_font_title, slider_font_desc,
        header_logo_url, header_logo_dark_url, header_logo_height, header_logo_alt,
        footer_logo_url, footer_logo_dark_url, footer_logo_height, footer_logo_alt,
        favicon_url,
        admin_logo_url, admin_logo_height, admin_logo_alt,
        mini_logo_url, mini_logo_height, mini_logo_alt,
        header_menu_align, header_menu_font_size, header_menu_gap,
        header_menu_letter_spacing, header_menu_font_weight, header_menu_text_transform,
        seo_meta_title, seo_meta_description, seo_meta_keywords,
        seo_google_verification, seo_ga4_id, seo_gtm_id, custom_head_scripts, custom_body_scripts, seo_og_image_url,
        seo_canonical_url, seo_indexing_enabled,
        seo_title_separator, seo_product_title_template, seo_product_desc_template,
        seo_category_title_template, seo_category_desc_template,
        seo_brand_title_template, seo_brand_desc_template,
        seo_blog_title_template, seo_blog_desc_template, seo_page_title_template,
        footer_features_active, footer_features,
        footer_description, contact_phone, contact_email, contact_address,
        footer_col2_title, footer_col3_title, footer_col4_title, footer_col5_title, footer_col5_desc,
        social_instagram, social_facebook, social_youtube, social_linkedin,
        footer_copyright_text, footer_brand_subtext, footer_mersis_no, footer_kep_address,
        footer_show_payment_badges,
        payment_logo_iyzico, payment_logo_mastercard, payment_logo_visa, payment_logo_amex, payment_logo_troy
      ) VALUES (
        1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41,
        $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59,
        $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77
      )
      ON CONFLICT (id) DO UPDATE SET
        logo_text = EXCLUDED.logo_text,
        logo_url = EXCLUDED.logo_url,
        font_family = EXCLUDED.font_family,
        font_size_base = EXCLUDED.font_size_base,
        h1_size = EXCLUDED.h1_size,
        h2_size = EXCLUDED.h2_size,
        h3_size = EXCLUDED.h3_size,
        h4_size = EXCLUDED.h4_size,
        slider_font_title = EXCLUDED.slider_font_title,
        slider_font_desc = EXCLUDED.slider_font_desc,
        header_logo_url = EXCLUDED.header_logo_url,
        header_logo_dark_url = EXCLUDED.header_logo_dark_url,
        header_logo_height = EXCLUDED.header_logo_height,
        header_logo_alt = EXCLUDED.header_logo_alt,
        footer_logo_url = EXCLUDED.footer_logo_url,
        footer_logo_dark_url = EXCLUDED.footer_logo_dark_url,
        footer_logo_height = EXCLUDED.footer_logo_height,
        footer_logo_alt = EXCLUDED.footer_logo_alt,
        favicon_url = EXCLUDED.favicon_url,
        admin_logo_url = EXCLUDED.admin_logo_url,
        admin_logo_height = EXCLUDED.admin_logo_height,
        admin_logo_alt = EXCLUDED.admin_logo_alt,
        mini_logo_url = EXCLUDED.mini_logo_url,
        mini_logo_height = EXCLUDED.mini_logo_height,
        mini_logo_alt = EXCLUDED.mini_logo_alt,
        header_menu_align = EXCLUDED.header_menu_align,
        header_menu_font_size = EXCLUDED.header_menu_font_size,
        header_menu_gap = EXCLUDED.header_menu_gap,
        header_menu_letter_spacing = EXCLUDED.header_menu_letter_spacing,
        header_menu_font_weight = EXCLUDED.header_menu_font_weight,
        header_menu_text_transform = EXCLUDED.header_menu_text_transform,
        seo_meta_title = EXCLUDED.seo_meta_title,
        seo_meta_description = EXCLUDED.seo_meta_description,
        seo_meta_keywords = EXCLUDED.seo_meta_keywords,
        seo_google_verification = EXCLUDED.seo_google_verification,
        seo_ga4_id = EXCLUDED.seo_ga4_id,
        seo_gtm_id = EXCLUDED.seo_gtm_id,
        custom_head_scripts = EXCLUDED.custom_head_scripts,
        custom_body_scripts = EXCLUDED.custom_body_scripts,
        seo_og_image_url = EXCLUDED.seo_og_image_url,
        seo_canonical_url = EXCLUDED.seo_canonical_url,
        seo_indexing_enabled = EXCLUDED.seo_indexing_enabled,
        seo_title_separator = EXCLUDED.seo_title_separator,
        seo_product_title_template = EXCLUDED.seo_product_title_template,
        seo_product_desc_template = EXCLUDED.seo_product_desc_template,
        seo_category_title_template = EXCLUDED.seo_category_title_template,
        seo_category_desc_template = EXCLUDED.seo_category_desc_template,
        seo_brand_title_template = EXCLUDED.seo_brand_title_template,
        seo_brand_desc_template = EXCLUDED.seo_brand_desc_template,
        seo_blog_title_template = EXCLUDED.seo_blog_title_template,
        seo_blog_desc_template = EXCLUDED.seo_blog_desc_template,
        seo_page_title_template = EXCLUDED.seo_page_title_template,
        footer_features_active = EXCLUDED.footer_features_active,
        footer_features = EXCLUDED.footer_features,
        footer_description = EXCLUDED.footer_description,
        contact_phone = EXCLUDED.contact_phone,
        contact_email = EXCLUDED.contact_email,
        contact_address = EXCLUDED.contact_address,
        footer_col2_title = EXCLUDED.footer_col2_title,
        footer_col3_title = EXCLUDED.footer_col3_title,
        footer_col4_title = EXCLUDED.footer_col4_title,
        footer_col5_title = EXCLUDED.footer_col5_title,
        footer_col5_desc = EXCLUDED.footer_col5_desc,
        social_instagram = EXCLUDED.social_instagram,
        social_facebook = EXCLUDED.social_facebook,
        social_youtube = EXCLUDED.social_youtube,
        social_linkedin = EXCLUDED.social_linkedin,
        footer_copyright_text = EXCLUDED.footer_copyright_text,
        footer_brand_subtext = EXCLUDED.footer_brand_subtext,
        footer_mersis_no = EXCLUDED.footer_mersis_no,
        footer_kep_address = EXCLUDED.footer_kep_address,
        footer_show_payment_badges = EXCLUDED.footer_show_payment_badges,
        payment_logo_iyzico = EXCLUDED.payment_logo_iyzico,
        payment_logo_mastercard = EXCLUDED.payment_logo_mastercard,
        payment_logo_visa = EXCLUDED.payment_logo_visa,
        payment_logo_amex = EXCLUDED.payment_logo_amex,
        payment_logo_troy = EXCLUDED.payment_logo_troy`,
      [
        logo_text || "Mağaza",
        logo_url || null,
        font_family || "Inter",
        font_size_base || "16px",
        h1_size || "2.5rem",
        h2_size || "2rem",
        h3_size || "1.75rem",
        h4_size || "1.5rem",
        slider_font_title || "Plus Jakarta Sans",
        slider_font_desc || "Inter",
        header_logo_url || "/brand/placeholder.svg",
        header_logo_dark_url || "/brand/placeholder.svg",
        header_logo_height ? parseInt(header_logo_height) : 40,
        header_logo_alt || logo_text || "Mağaza",
        footer_logo_url || "/brand/placeholder.svg",
        footer_logo_dark_url || "/brand/placeholder.svg",
        footer_logo_height ? parseInt(footer_logo_height) : 36,
        footer_logo_alt || logo_text || "Mağaza",
        favicon_url || "/brand/placeholder.svg",
        admin_logo_url || "/brand/placeholder.svg",
        admin_logo_height ? parseInt(admin_logo_height) : 32,
        admin_logo_alt || logo_text || "Yönetim Paneli",
        mini_logo_url || "/brand/placeholder.svg",
        mini_logo_height ? parseInt(mini_logo_height) : 24,
        mini_logo_alt || logo_text || "Mağaza",
        header_menu_align || "center",
        header_menu_font_size || "13px",
        header_menu_gap || "16px",
        header_menu_letter_spacing || "0",
        header_menu_font_weight || "600",
        header_menu_text_transform || "none",
        seo_meta_title || null,
        seo_meta_description || null,
        seo_meta_keywords || null,
        seo_google_verification || null,
        seo_ga4_id || null,
        seo_gtm_id || null,
        custom_head_scripts || null,
        custom_body_scripts || null,
        seo_og_image_url || null,
        seo_canonical_url || null,
        seo_indexing_enabled === true,
        seo_title_separator || "|",
        seo_product_title_template || "%urun_adi% %ayirici% %site_adi%",
        seo_product_desc_template || "%urun_adi% ürününü %site_adi% üzerinde inceleyin.",
        seo_category_title_template || "%kategori% Modelleri ve Fiyatları %ayirici% %site_adi%",
        seo_category_desc_template || "%kategori% ürünlerini %site_adi% üzerinde inceleyin.",
        seo_brand_title_template || "%marka% Ürünleri ve Fiyatları %ayirici% %site_adi%",
        seo_brand_desc_template || "%marka% ürünlerini %site_adi% üzerinde inceleyin.",
        seo_blog_title_template || "%yazi_basligi% %ayirici% %site_adi%",
        seo_blog_desc_template || "%yazi_ozeti%",
        seo_page_title_template || "%sayfa_adi% %ayirici% %site_adi%",
        footer_features_active === true,
        footer_features ? JSON.stringify(footer_features) : null,
        footer_description || null,
        contact_phone || null,
        contact_email || null,
        contact_address || null,
        footer_col2_title || null,
        footer_col3_title || null,
        footer_col4_title || null,
        footer_col5_title || null,
        footer_col5_desc || null,
        social_instagram || null,
        social_facebook || null,
        social_youtube || null,
        social_linkedin || null,
        footer_copyright_text || null,
        footer_brand_subtext || null,
        footer_mersis_no || null,
        footer_kep_address || null,
        footer_show_payment_badges === true,
        payment_logo_iyzico || null,
        payment_logo_mastercard || null,
        payment_logo_visa || null,
        payment_logo_amex || null,
        payment_logo_troy || null,
      ]
    )

    revalidatePath("/", "layout")
    return NextResponse.json({ success: true })
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
